name: CI

on: push

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt install -y ffmpeg
        pip install -e .

    - name: Download test data
      run: python download_test_data.py --max-negative-samples 100

    - name: Run benchmark
      run: python benchmark.py
        
    - name: Check for uncommitted changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Error: There are uncommitted changes after running the workflow:"
          git status
          git diff
          exit 1
        fi
